dataset:
  root: ..
  IRSTD-1k:
    split_method: "6_4"
    size: 512
    model: PBT
    batch: 4
    aug: 0.
  MFIRST:
    split_method: "6_4"
    size: 128
    model: PBT
  NUAA-SIRST:
    split_method: "6_4"
    size: 512
    model: PBT
    batch: 8
    aug: 0.
  NUDT-SIRST:
    split_method: "6_4"
    size: 256
    model: PBT
    batch: 16
    aug: 0.
  IRSTD-Air:
    split_method: "6_4"
    size: 256
    model: PBT
    batch: 16
    aug: 0.
  track1_train:
    split_method: "1_2"
    size: 512
    model: PBT
    batch: 16
    aug: 0.
